language: node_js
cache:
  directories:
    - node_modules
node_js:
  - 10
script:
  - npm install -g degit && degit osdevisnot/starter-typescript-library example-library && cd example-library && node setup.js && npm run build && npm test
