language: node_js
cache:
  directories:
    - node_modules
node_js:
  - 10
deploy:
  provider: script
  script: 'echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > $HOME/.npmrc && npm version patch && npm publish && git push --follow-tags'
