language: node_js
cache:
  directories:
    - node_modules
node_js:
  - 8
  - 10
script: degit osdevisnot/starter-typescript-library example-library && cd example-library && node setup.js && npm test && npm run build
